title = "Starlit"
reload = true

[appbar]
  enabled = true

# The output directory for the `starlit render` command.
[render]
  output_folder = "dist"

[spaces.home]
  path = "/"
  type = "pages"
  title = "Starlit"
  name = "Home"
  icon = "bi bi-stars"

[spaces.home.sidebar]
  enabled = false

[spaces.docs]
  path = "/docs/"
  type = "pages"
  title = "Starlit Documentation"
  icon = "bi bi-book"
