title = "Starlit"

[appbar]
  enabled = false

# The output directory for the `starlit render` command.
[render]
  output_folder = "dist"

[app.home]
  path = "/"
  type = "pages"

[app.docs]
  path = "/docs/"
  type = "pages"
  title = "Starlit Documentation"
