// Code generated by index_vendored_packages; DO NOT EDIT
package web

var vendoredLibraries = map[string]string {
    "js-base64": "js-base64@3.6.0",
    "starboard-notebook": "starboard-notebook@0.9.4",
    "starboard-wrap": "starboard-wrap@0.3.2",

}

// Given "starboard-notebook", returns the package name with version "starboard-notebook@0.9.4"
func GetVendoredPackage(name string) string {
	return vendoredLibraries[name]
}
