// Code generated by index_vendored_packages; DO NOT EDIT
package web

var vendoredLibraries = map[string]string {
    "starboard-notebook": "starboard-notebook@0.12.3",
    "starboard-wrap": "starboard-wrap@0.4.0",

}

// Given "starboard-notebook", returns the package name with version "starboard-notebook@0.9.4"
func GetVendoredPackage(name string) string {
	return vendoredLibraries[name]
}
